name: dot

on:
  push:
    branches: main 
  schedule:
    # Chạy mỗi 30 phút (tức là: 00:00, 00:30, 01:00, 01:30, ...)
    - cron: '*/30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Giới hạn tối đa 6 tiếng mỗi lần chạy
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy bot
        run: |
          python run1.py &
          python run2.py &
          python run3.py &
          python run4.py &
          python run5.py &
          sleep 21600
